-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "steps" SET DEFAULT '3',
ALTER COLUMN "steps" SET DATA TYPE TEXT,
ALTER COLUMN "timeResting" SET DEFAULT '5',
ALTER COLUMN "timeResting" SET DATA TYPE TEXT;
