-- AlterTable
ALTER TABLE "Todo" ADD COLUMN     "steps" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "timeDuration" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "timeResting" INTEGER NOT NULL DEFAULT 5;
